import { mkdir, readdir, watch } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "@mdx-js/mdx";
import matter from "gray-matter";
import rehypeSlug from "rehype-slug";
import remarkGfm from "remark-gfm";
import { z } from "zod";

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, "..");
const contentDir = join(rootDir, "content");
const generatedDir = join(rootDir, "src", "generated");
const generatedMdxDir = join(generatedDir, "mdx");
const watchMode = process.argv.includes("--watch");

const frontmatterSchema = z.object({
	path: z.string().min(1),
	title: z.string().min(1),
	description: z.string().min(1),
});

type Frontmatter = z.infer<typeof frontmatterSchema>;

export interface TocEntry {
	id: string;
	label: string;
	depth: number;
}

function slugify(text: string): string {
	// Match rehype-slug's heading ids closely enough that TOC links stay in sync.
	return text
		.toLowerCase()
		.replace(/[^a-z0-9\s-]/g, "")
		.trim()
		.replace(/\s/g, "-");
}

function extractToc(content: string): TocEntry[] {
	const entries: TocEntry[] = [];
	const headingRe = /^(#{2})\s+(.+)$/gm;
	let match: RegExpExecArray | null;

	while ((match = headingRe.exec(content)) !== null) {
		const depth = 2;
		const label = match[2].trim();
		const id = slugify(label);
		entries.push({ id, label, depth });
	}

	return entries;
}

function mdxBaseToComponentVar(base: string): string {
	const camel = base.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
	return camel.charAt(0).toUpperCase() + camel.slice(1) + "Component";
}

async function discoverMdxFiles(): Promise<string[]> {
	const entries = await readdir(contentDir, { withFileTypes: true });
	const files = entries
		.filter((e) => e.isFile() && e.name.endsWith(".mdx"))
		.map((e) => e.name.replace(/\.mdx$/, ""));
	return files.sort((a, b) => {
		// index first, then alphabetical
		if (a === "index") return -1;
		if (b === "index") return 1;
		return a.localeCompare(b);
	});
}

async function build(): Promise<void> {
	await mkdir(generatedDir, { recursive: true });
	await mkdir(generatedMdxDir, { recursive: true });

	const mdxBases = await discoverMdxFiles();
	const pages: Array<{
		path: string;
		title: string;
		description: string;
		componentVar: string;
		toc: TocEntry[];
	}> = [];

	for (const base of mdxBases) {
		const filePath = join(contentDir, `${base}.mdx`);
		const rawSource = await Bun.file(filePath).text();
		const parsed = matter(rawSource);
		const frontmatter = frontmatterSchema.parse(parsed.data);
		const toc = extractToc(parsed.content);

		const compiled = await compile(parsed.content, {
			jsxImportSource: "react",
			providerImportSource: "../../site/ui",
			remarkPlugins: [remarkGfm],
			rehypePlugins: [rehypeSlug],
		});

		const componentVar = mdxBaseToComponentVar(base);
		const outputPath = join(generatedMdxDir, `${base}.tsx`);
		await Bun.write(
			outputPath,
			`// @ts-nocheck\n/* eslint-disable */\n/* auto-generated by scripts/build-content.ts */\n${String(compiled)}`,
		);

		pages.push({
			path: frontmatter.path,
			title: frontmatter.title,
			description: frontmatter.description,
			componentVar,
			toc,
		});
	}

	const importStatements = pages.map((p, i) => {
		const fileBase = mdxBases[i];
		return `import ${p.componentVar} from "./mdx/${fileBase}";`;
	});

	const pageEntries = pages.map(
		(p) => `	${JSON.stringify(p.path)}: {
		path: ${JSON.stringify(p.path)},
		title: ${JSON.stringify(p.title)},
		description: ${JSON.stringify(p.description)},
		component: ${p.componentVar},
		toc: ${JSON.stringify(p.toc, null, 2)},
	}`,
	);

	const contentFile = `/* auto-generated by scripts/build-content.ts */
import type { SitePage, TocEntry } from "../site/types";

${importStatements.join("\n")}

export const sitePages = ${JSON.stringify(
		pages.map((p) => ({ path: p.path, title: p.title })),
		null,
		2,
	)};

const pagesMap: Record<string, SitePage> = {
${pageEntries.join(",\n")}
};

export function getPage(path: string): SitePage | undefined {
	return pagesMap[path];
}
`;

	await Bun.write(join(generatedDir, "content.ts"), contentFile);
	console.log(
		`built ${pages.length} page(s): ${pages.map((p) => p.path).join(", ")}`,
	);
}

async function watchAndBuild(): Promise<void> {
	await build();
	console.log("watching content/**/*.mdx");

	let timeout: ReturnType<typeof setTimeout> | null = null;

	for await (const _event of watch(contentDir, { recursive: true })) {
		if (timeout) {
			clearTimeout(timeout);
		}

		timeout = setTimeout(() => {
			void build().catch((error) => {
				console.error(error);
			});
		}, 80);
	}
}

if (watchMode) {
	await watchAndBuild();
} else {
	await build();
}
