import fs from "node:fs";
import path from "node:path";
import { buildDemoPlaygroundWorkspace } from "../../src/ast/demo/demo-workspace-builder";
import { writeTextArtifact } from "../../src/ast/shared/emit/ts-emit-core";

const outputPath = path.resolve(
	import.meta.dirname,
	"..",
	"src",
	"generated",
	"demo-playground-files.ts",
);

const playgroundSourcesDir = path.resolve(
	import.meta.dirname,
	"..",
	"playground-sources",
);

const mockPackageSource = fs.readFileSync(
	path.join(playgroundSourcesDir, "orm-package-mock.ts"),
	"utf-8",
);
const mockBaseSource = fs.readFileSync(
	path.join(playgroundSourcesDir, "orm-base-mock.ts"),
	"utf-8",
);

const { files, databaseEntryFile, agentEntryFile } =
	buildDemoPlaygroundWorkspace({
		mockPackageSource,
		mockBaseSource,
	});

const content = `/* auto-generated by website/scripts/build-demo-playground.ts — do not edit */
export const databaseEntryFile = ${JSON.stringify(databaseEntryFile)};
export const agentEntryFile = ${JSON.stringify(agentEntryFile)};
export const playgroundFiles = ${JSON.stringify(files, null, 2)} satisfies Record<string, string>;
`;

writeTextArtifact({ filePath: outputPath, content });

// biome-ignore lint/suspicious/noConsole: script reports generated file count
console.log(
	`built demo playground workspace with ${Object.keys(files).length} files`,
);
