import { mkdir, readdir, watch } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { z } from "zod";
import { createHeadingSlugFactory } from "../src/site/slugify";
import { type SitePath, sitePaths, type TocEntry } from "../src/site/types";

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, "..");
const contentDir = join(rootDir, "content");
const generatedDir = join(rootDir, "src", "generated");
const watchMode = process.argv.includes("--watch");

const metadataSchema = z.object({
	path: z.enum(sitePaths),
	title: z.string().min(1),
	description: z.string().min(1),
});

function extractExportedMetadata(
	source: string,
): Record<string, unknown> | null {
	const marker = "export const metadata = ";
	const start = source.indexOf(marker);
	if (start === -1) return null;

	const braceStart = start + marker.length;
	if (source[braceStart] !== "{") return null;

	let depth = 0;
	let i = braceStart;
	while (i < source.length) {
		if (source[i] === "{") depth++;
		else if (source[i] === "}") depth--;
		if (depth === 0) break;
		i++;
	}
	if (depth !== 0) return null;

	const objectLiteral = source.slice(braceStart, i + 1);
	return new Function(`return ${objectLiteral}`)() as Record<string, unknown>;
}

/** Strip MDX inline-code backticks from heading text for sidebar / TOC display only. */
function tocDisplayLabel(rawHeadingLine: string): string {
	return rawHeadingLine.replace(/`/g, "").trim();
}

function extractToc(content: string): TocEntry[] {
	const entries: TocEntry[] = [];
	const nextId = createHeadingSlugFactory();
	/** h2–h4 only: matches in-page section titles and subsections (e.g. function names under API sections). */
	const headingRe = /^(#{2,4})\s+(.+)$/gm;
	let match = headingRe.exec(content);

	while (match !== null) {
		const depth = match[1].length;
		const rawLabel = match[2].trim();
		const id = nextId(rawLabel);
		const label = tocDisplayLabel(rawLabel);
		entries.push({ id, label, depth });
		match = headingRe.exec(content);
	}

	return entries;
}

function toPascalCase(base: string): string {
	return base
		.split(/[-_]/)
		.map((part) => part.charAt(0).toUpperCase() + part.slice(1))
		.join("");
}

async function discoverMdxFiles(): Promise<string[]> {
	const entries = await readdir(contentDir, { withFileTypes: true });
	const files = entries
		.filter((e) => e.isFile() && e.name.endsWith(".mdx"))
		.map((e) => e.name.replace(/\.mdx$/, ""));
	const indexPages = files.filter((name) => name === "index");
	const nonIndexPages = files
		.filter((name) => name !== "index")
		.sort((left, right) => left.localeCompare(right));
	return [...indexPages, ...nonIndexPages];
}

async function build(): Promise<void> {
	await mkdir(generatedDir, { recursive: true });

	const mdxBases = await discoverMdxFiles();
	const pages: Array<{
		path: SitePath;
		title: string;
		description: string;
		fileBase: string;
		varName: string;
		toc: TocEntry[];
	}> = [];

	for (const base of mdxBases) {
		const filePath = join(contentDir, `${base}.mdx`);
		const rawSource = await Bun.file(filePath).text();
		const raw = extractExportedMetadata(rawSource);
		if (!raw) {
			throw new Error(
				`[build-mdx-content] ${base}.mdx: missing "export const metadata = { ... }"`,
			);
		}
		const meta = metadataSchema.parse(raw);
		const toc = extractToc(rawSource);

		pages.push({
			path: meta.path,
			title: meta.title,
			description: meta.description,
			fileBase: base,
			varName: `${toPascalCase(base)}Content`,
			toc,
		});
	}

	const imports = pages
		.map((p) => `import ${p.varName} from "../../content/${p.fileBase}.mdx";`)
		.join("\n");

	const pageEntries = pages.map(
		(p) => `	${JSON.stringify(p.path)}: {
		path: ${JSON.stringify(p.path)},
		title: ${JSON.stringify(p.title)},
		description: ${JSON.stringify(p.description)},
		component: ${p.varName},
		toc: ${JSON.stringify(p.toc, null, 2)},
	}`,
	);

	const contentFile = `/* auto-generated by scripts/build-mdx-content.ts — do not edit */
import type { SitePage, SitePath } from "../site/types";
${imports}

export const sitePages = ${JSON.stringify(
		pages.map((p) => ({ path: p.path, title: p.title })),
		null,
		2,
	)} satisfies ReadonlyArray<Pick<SitePage, "path" | "title">>;

const pagesMap = {
${pageEntries.join(",\n")}
} satisfies Record<SitePath, SitePage>;

export function getPage(path: SitePath): SitePage | undefined {
	return pagesMap[path];
}
`;

	await Bun.write(join(generatedDir, "content.ts"), contentFile);
	console.log(
		`built ${pages.length} page(s): ${pages.map((p) => p.path).join(", ")}`,
	);
}

async function watchAndBuild(): Promise<void> {
	await build();
	console.log("watching content/**/*.mdx");

	let timeout: ReturnType<typeof setTimeout> | null = null;

	for await (const _event of watch(contentDir, { recursive: true })) {
		if (timeout) {
			clearTimeout(timeout);
		}

		timeout = setTimeout(() => {
			void build().catch((error) => {
				console.error(error);
			});
		}, 80);
	}
}

if (watchMode) {
	await watchAndBuild();
} else {
	await build();
}
