import fs from "fs";
import path from "path";
import * as ts from "typescript";
import type { AgentIcon } from "../../client/agent/AgentClient";
import { camelize, toPascalCase } from "../../helpers";
import { createNameImport } from "../shared/ast-builders";
import { AGENTS_DIR, AST_IMPORT_PATHS, AST_RUNTIME_CONSTANTS } from "../shared/constants";
import { emitValueAsExpression } from "../shared/emit/emit-value-as-expression";
import {
	createEmitContext,
	finalizeGeneratedSourceWithTrailingNewline,
	insertBlankLineAfterDoubleSlashBanner,
	printTsNodes,
	transpileTsToJs,
	writeTextArtifact,
} from "../shared/emit/ts-emit-core";
import { TS_EMIT_OPTIONS_GENERATED } from "../shared/emit/ts-emit-options";

export interface AgentModuleBuildResult {
	statementSegments: readonly (readonly ts.Statement[])[];
	agentId: string;
	agentName: string;
	agentModuleName: string;
}

function addLeadingSectionComment(node: ts.Statement, text: string): void {
	ts.addSyntheticLeadingComment(
		node,
		ts.SyntaxKind.SingleLineCommentTrivia,
		` ${text}`,
		true,
	);
}

function addGeneratedAgentModuleBanner(
	agentClientImport: ts.ImportDeclaration,
	cliGenerateCommand: string,
): void {
	ts.addSyntheticLeadingComment(
		agentClientImport,
		ts.SyntaxKind.SingleLineCommentTrivia,
		" Generated by @haustle/notion-orm — do not edit manually.",
		true,
	);
	ts.addSyntheticLeadingComment(
		agentClientImport,
		ts.SyntaxKind.SingleLineCommentTrivia,
		` Regenerate with \`${cliGenerateCommand}\` (or your package script).`,
		true,
	);
}

function printAndTranspileAgentModule(args: {
	statementSegments: readonly (readonly ts.Statement[])[];
	agentFileBasename: string;
}): { tsCode: string; jsCode: string } {
	const context = createEmitContext({
		fileName: `${args.agentFileBasename}.ts`,
	});
	const printed = args.statementSegments
		.map((segment) => printTsNodes({ nodes: segment, context }).trimEnd())
		.join("\n\n");
	let tsCode = insertBlankLineAfterDoubleSlashBanner(printed);
	tsCode = finalizeGeneratedSourceWithTrailingNewline(tsCode);
	const jsCode = transpileTsToJs({
		typescriptCode: tsCode,
		module: TS_EMIT_OPTIONS_GENERATED.module,
		target: TS_EMIT_OPTIONS_GENERATED.target,
	});
	return { tsCode, jsCode };
}

export function buildAgentModuleNodes(args: {
	agentId: string;
	agentName: string;
	agentIcon: AgentIcon;
	agentModuleName?: string;
}): AgentModuleBuildResult {
	const agentModuleName = args.agentModuleName ?? camelize(args.agentName);
	const agentClientImport = createNameImport({
		namedImport: "AgentClient",
		path: AST_IMPORT_PATHS.AGENT_CLIENT,
	});
	addGeneratedAgentModuleBanner(
		agentClientImport,
		AST_RUNTIME_CONSTANTS.CLI_GENERATE_COMMAND,
	);

	const idVariable = ts.factory.createVariableStatement(
		undefined,
		ts.factory.createVariableDeclarationList(
			[
				ts.factory.createVariableDeclaration(
					ts.factory.createIdentifier("id"),
					undefined,
					undefined,
					ts.factory.createStringLiteral(args.agentId),
				),
			],
			ts.NodeFlags.Const,
		),
	);
	addLeadingSectionComment(idVariable, "Identity (Notion agent id)");

	const nameVariable = ts.factory.createVariableStatement(
		undefined,
		ts.factory.createVariableDeclarationList(
			[
				ts.factory.createVariableDeclaration(
					ts.factory.createIdentifier("name"),
					undefined,
					undefined,
					ts.factory.createStringLiteral(args.agentName),
				),
			],
			ts.NodeFlags.Const,
		),
	);
	addLeadingSectionComment(nameVariable, "Display name (from Notion)");

	const iconValue = emitValueAsExpression(args.agentIcon);

	const agentClientFunction = ts.factory.createVariableStatement(
		[ts.factory.createModifier(ts.SyntaxKind.ExportKeyword)],
		ts.factory.createVariableDeclarationList(
			[
				ts.factory.createVariableDeclaration(
					ts.factory.createIdentifier(toPascalCase(agentModuleName)),
					undefined,
					undefined,
					ts.factory.createArrowFunction(
						undefined,
						undefined,
						[
							ts.factory.createParameterDeclaration(
								undefined,
								undefined,
								ts.factory.createIdentifier("auth"),
								undefined,
								ts.factory.createKeywordTypeNode(ts.SyntaxKind.StringKeyword),
								undefined,
							),
						],
						undefined,
						undefined,
						ts.factory.createNewExpression(
							ts.factory.createIdentifier("AgentClient"),
							undefined,
							[
								ts.factory.createObjectLiteralExpression(
									[
										ts.factory.createPropertyAssignment(
											ts.factory.createIdentifier("auth"),
											ts.factory.createIdentifier("auth"),
										),
										ts.factory.createPropertyAssignment(
											ts.factory.createIdentifier("id"),
											ts.factory.createIdentifier("id"),
										),
										ts.factory.createPropertyAssignment(
											ts.factory.createIdentifier("name"),
											ts.factory.createIdentifier("name"),
										),
										ts.factory.createPropertyAssignment(
											ts.factory.createIdentifier("icon"),
											iconValue,
										),
									],
									true,
								),
							],
						),
					),
				),
			],
			ts.NodeFlags.Const,
		),
	);
	addLeadingSectionComment(agentClientFunction, "Agent client factory");

	const statementSegments: readonly (readonly ts.Statement[])[] = [
		[agentClientImport],
		[idVariable],
		[nameVariable],
		[agentClientFunction],
	];

	return {
		statementSegments,
		agentId: args.agentId,
		agentName: args.agentName,
		agentModuleName,
	};
}

export function renderAgentModule(args: {
	agentId: string;
	agentName: string;
	agentIcon: AgentIcon;
	agentModuleName?: string;
}): {
	tsCode: string;
	jsCode: string;
	agentId: string;
	agentName: string;
	agentModuleName: string;
} {
	const { statementSegments, agentId, agentName, agentModuleName } =
		buildAgentModuleNodes(args);
	const { tsCode, jsCode } = printAndTranspileAgentModule({
		statementSegments,
		agentFileBasename: toPascalCase(agentModuleName),
	});
	return { tsCode, jsCode, agentId, agentName, agentModuleName };
}

export async function createTypescriptFileForAgent(args: {
	agentId: string;
	agentName: string;
	agentModuleName: string;
	agentIcon: AgentIcon;
}): Promise<void> {
	const { statementSegments, agentModuleName } = buildAgentModuleNodes(args);

	if (!fs.existsSync(AGENTS_DIR)) {
		fs.mkdirSync(AGENTS_DIR, { recursive: true });
	}

	const agentFileBasename = toPascalCase(agentModuleName);
	const { tsCode, jsCode } = printAndTranspileAgentModule({
		statementSegments,
		agentFileBasename,
	});
	const tsPath = path.resolve(AGENTS_DIR, `${agentFileBasename}.ts`);
	const jsPath = path.resolve(AGENTS_DIR, `${agentFileBasename}.js`);
	writeTextArtifact({ filePath: tsPath, content: tsCode });
	writeTextArtifact({ filePath: jsPath, content: jsCode });
}
