// Generated by @haustle/notion-orm — do not edit manually.
// Regenerate with `notion sync` (or your package script).
// Database client factories (generated under ./databases/).

import type { TaskDb } from "./databases/TaskDb";

// Agent client factories (generated under ./agents/).
import type { MealAgent } from "./agents/MealAgent";

// Package imports: NotionORMBase, config types, and client classes.
import { NotionORMBase, AgentClient, DatabaseClient } from "@haustle/notion-orm/build/src/base";
export type { NotionConfigType } from "@haustle/notion-orm/build/src/base";
export { AgentClient, DatabaseClient } from "@haustle/notion-orm/build/src/base";

/**
 * Generated Notion ORM entrypoint for this project.
 * `databases` and `agents` expose typed factories produced from your synced Notion workspace.
 */
export class NotionORM extends NotionORMBase {
    /**
     * Typed database client factories.
     * Keys match the `databases` entries in your Notion config; each value is a factory bound to this client's `auth` token.
     */
    public databases: {
        taskDb: ReturnType<typeof TaskDb>;
    };
    /**
     * Typed agent client factories.
     * Keys match the `agents` entries in your Notion config; each value is a factory bound to this client's `auth` token.
     */
    public agents: {
        mealAgent: ReturnType<typeof MealAgent>;
    };
    constructor(config: {
        auth?: string;
    });
}

