"use strict";
// Generated by @haustle/notion-orm — do not edit manually.
// Regenerate with `notion sync` (or your package script).
Object.defineProperty(exports, "__esModule", { value: true });
exports.CustomerOrders = void 0;
const notion_orm_1 = require("@haustle/notion-orm");
// Column metadata
const columns = {
    "orderName": {
        columnName: "Order Name",
        type: "title"
    },
    "notes": {
        columnName: "Notes",
        type: "rich_text"
    },
    "total": {
        columnName: "Total",
        type: "number"
    },
    "orderDate": {
        columnName: "Order Date",
        type: "date"
    },
    "paid": {
        columnName: "Paid",
        type: "checkbox"
    },
    "customerEmail": {
        columnName: "Customer Email",
        type: "email"
    },
    "customerPhone": {
        columnName: "Customer Phone",
        type: "phone_number"
    },
    "receiptUrl": {
        columnName: "Receipt URL",
        type: "url"
    }
};
// Database client factory
const CustomerOrders = (auth) => {
    return new notion_orm_1.DatabaseClient({
        id: "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4",
        columns: columns,
        name: "Customer Orders",
        auth
    });
};
exports.CustomerOrders = CustomerOrders;
