// Generated by @haustle/notion-orm — do not edit manually.
// Regenerate with `notion sync` (or your package script).

import type { DatabaseColumns, DatabaseDefinition, InferDatabaseSchema, Query } from "@haustle/notion-orm";
import { DatabaseClient } from "@haustle/notion-orm";

// Column metadata
const columns = {
    "name": {
        columnName: "Name",
        type: "title"
    },
    "attachments": {
        columnName: "Attachments",
        type: "files"
    },
    "assignees": {
        columnName: "Assignees",
        type: "people"
    },
    "relatedItems": {
        columnName: "Related Items",
        type: "relation",
        relatedDatabaseId: "d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1"
    },
    "createdBy": {
        columnName: "Created By",
        type: "created_by"
    },
    "lastEditedBy": {
        columnName: "Last Edited By",
        type: "last_edited_by"
    },
    "createdAt": {
        columnName: "Created At",
        type: "created_time"
    },
    "updatedAt": {
        columnName: "Updated At",
        type: "last_edited_time"
    }
} as const satisfies DatabaseColumns;

// Row types (TypeScript)
export type DatabaseSchemaType = InferDatabaseSchema<typeof columns>;
// Typed database query arguments
export type QuerySchemaType = Query<DatabaseDefinition<typeof columns>>;
// Database client factory
export const EdgeCases = (auth: string) => {
    return new DatabaseClient<DatabaseDefinition<typeof columns>>({
        id: "c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6",
        columns: columns,
        name: "Edge Cases",
        auth
    });
};
