"use strict";
// Generated by @haustle/notion-orm — do not edit manually.
// Regenerate with `notion sync` (or your package script).
Object.defineProperty(exports, "__esModule", { value: true });
exports.EdgeCases = void 0;
const notion_orm_1 = require("@haustle/notion-orm");
// Column metadata
const columns = {
    "name": {
        columnName: "Name",
        type: "title"
    },
    "attachments": {
        columnName: "Attachments",
        type: "files"
    },
    "assignees": {
        columnName: "Assignees",
        type: "people"
    },
    "relatedItems": {
        columnName: "Related Items",
        type: "relation",
        relatedDatabaseId: "d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1"
    },
    "createdBy": {
        columnName: "Created By",
        type: "created_by"
    },
    "lastEditedBy": {
        columnName: "Last Edited By",
        type: "last_edited_by"
    },
    "createdAt": {
        columnName: "Created At",
        type: "created_time"
    },
    "updatedAt": {
        columnName: "Updated At",
        type: "last_edited_time"
    }
};
// Database client factory
const EdgeCases = (auth) => {
    return new notion_orm_1.DatabaseClient({
        id: "c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6",
        columns: columns,
        name: "Edge Cases",
        auth
    });
};
exports.EdgeCases = EdgeCases;
