// Generated by @haustle/notion-orm — do not edit manually.
// Regenerate with `notion sync` (or your package script).

import type { DatabaseColumns, DatabaseDefinition, InferCreateSchema, InferDatabaseSchema, Query } from "@haustle/notion-orm";
import { DatabaseClient } from "@haustle/notion-orm";

// Option literals for select/status/multi_select columns
export const CategoryPropertyValues = [
    "Electronics",
    "Clothing",
    "Food"
] as const;

export const AvailabilityPropertyValues = [
    "In Stock",
    "Out of Stock",
    "Backordered"
] as const;

export const TagsPropertyValues = [
    "New",
    "Sale",
    "Featured"
] as const;

// Column metadata
const columns = {
    "itemName": {
        columnName: "Item Name",
        type: "title"
    },
    "category": {
        columnName: "Category",
        type: "select",
        options: CategoryPropertyValues
    },
    "availability": {
        columnName: "Availability",
        type: "status",
        options: AvailabilityPropertyValues
    },
    "tags": {
        columnName: "Tags",
        type: "multi_select",
        options: TagsPropertyValues
    },
    "sku": {
        columnName: "SKU",
        type: "unique_id"
    },
    "price": {
        columnName: "Price",
        type: "number"
    }
} as const satisfies DatabaseColumns;

// Row types (TypeScript)
export type PageSchema = InferDatabaseSchema<typeof columns>;
// Create/update payload types (writable columns only)
export type CreateSchema = InferCreateSchema<typeof columns>;
// Typed database query arguments
export type QuerySchema = Query<DatabaseDefinition<typeof columns>>;
// Database client factory
export const InventoryItems = (auth: string) => {
    return new DatabaseClient<DatabaseDefinition<typeof columns>>({
        id: "b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5",
        columns: columns,
        name: "Inventory Items",
        auth
    });
};
