"use strict";
// Generated by @haustle/notion-orm — do not edit manually.
// Regenerate with `notion sync` (or your package script).
Object.defineProperty(exports, "__esModule", { value: true });
exports.InventoryItems = exports.TagsPropertyValues = exports.AvailabilityPropertyValues = exports.CategoryPropertyValues = void 0;
const notion_orm_1 = require("@haustle/notion-orm");
// Option literals for select/status/multi_select columns
exports.CategoryPropertyValues = [
    "Electronics",
    "Clothing",
    "Food"
];
exports.AvailabilityPropertyValues = [
    "In Stock",
    "Out of Stock",
    "Backordered"
];
exports.TagsPropertyValues = [
    "New",
    "Sale",
    "Featured"
];
// Column metadata
const columns = {
    "itemName": {
        columnName: "Item Name",
        type: "title"
    },
    "category": {
        columnName: "Category",
        type: "select",
        options: exports.CategoryPropertyValues
    },
    "availability": {
        columnName: "Availability",
        type: "status",
        options: exports.AvailabilityPropertyValues
    },
    "tags": {
        columnName: "Tags",
        type: "multi_select",
        options: exports.TagsPropertyValues
    },
    "sku": {
        columnName: "SKU",
        type: "unique_id"
    },
    "price": {
        columnName: "Price",
        type: "number"
    }
};
// Database client factory
const InventoryItems = (auth) => {
    return new notion_orm_1.DatabaseClient({
        id: "b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5",
        columns: columns,
        name: "Inventory Items",
        auth
    });
};
exports.InventoryItems = InventoryItems;
