/**
 * Database file writer for generated Notion data sources.
 * Converts a Notion schema response into emitted TS/JS modules and column
 * metadata consumed by the generated client layer.
 */
import type {
	DataSourceObjectResponse,
	GetDataSourceResponse,
} from "@notionhq/client/build/src/api-endpoints.js";
import fs from "fs";
import path from "path";
import * as ts from "typescript";
import {
	isColumnTypesWithOptions,
	isSupportedPropertyType,
	type SupportedNotionColumnType,
} from "../../client/database/types";
import { camelize, toUndashedNotionId } from "../../helpers";
import { toNotionDatabaseId } from "../../client/database/types/notion-database-id";
import {
	createColumnNameToColumnProperties,
	createDatabaseClassExport,
	createCreateSchemaTypeExport,
	createPageSchemaTypeExport,
	createNameImport,
	createQuerySchemaTypeExport,
	createTypeOnlyNamedImports,
	type GeneratedColumnMetadataMap,
	toPascalCase,
} from "../shared/ast-builders";
import {
	AST_FS_PATHS,
	AST_IMPORT_PATHS,
	AST_RUNTIME_CONSTANTS,
} from "../shared/constants";
import {
	createEmitContext,
	finalizeGeneratedSourceWithTrailingNewline,
	printTsNodes,
	transpileTsToJs,
	writeTextArtifact,
} from "../shared/emit/ts-emit-core";
import { TS_EMIT_OPTIONS_GENERATED } from "../shared/emit/ts-emit-options";
import {
	propertyASTGenerators,
	type SupportedNotionProperty,
} from "./notion-column-generators";

type NotionDataSourceProperty = DataSourceObjectResponse["properties"][string];

/** Narrows Notion properties to the subset supported by our emitters. */
function isSupportedNotionProperty(
	property: NotionDataSourceProperty,
): property is SupportedNotionProperty {
	return isSupportedPropertyType(property.type);
}

function addLeadingSectionComment(node: ts.Statement, text: string): void {
	ts.addSyntheticLeadingComment(
		node,
		ts.SyntaxKind.SingleLineCommentTrivia,
		` ${text}`,
		true,
	);
}

function addGeneratedDatabaseModuleBanner(
	notionOrmImport: ts.ImportDeclaration,
	cliGenerateCommand: string,
): void {
	ts.addSyntheticLeadingComment(
		notionOrmImport,
		ts.SyntaxKind.SingleLineCommentTrivia,
		" Generated by @haustle/notion-orm — do not edit manually.",
		true,
	);
	ts.addSyntheticLeadingComment(
		notionOrmImport,
		ts.SyntaxKind.SingleLineCommentTrivia,
		` Regenerate with \`${cliGenerateCommand}\` (or your package script).`,
		true,
	);
}

/**
 * Prefer the live Notion title when present, but fall back to a stable label so
 * generation can still succeed for sparse payloads.
 */
function getDataSourceDisplayName(args: {
	dataSourceResponse: GetDataSourceResponse;
	normalizedDataSourceId: string;
}): string {
	if ("title" in args.dataSourceResponse) {
		const title = args.dataSourceResponse.title?.[0]?.plain_text?.trim();
		if (title) {
			return title;
		}
	}
	return `Database ${args.normalizedDataSourceId.slice(0, 8)}`;
}

interface DatabaseModuleBuildResult {
	/** Statement groups printed with a blank line between groups for readability. */
	statementSegments: readonly (readonly ts.Statement[])[];
	databaseName: string;
	databaseModuleName: string;
	databaseId: string;
}

/** Inserts a blank line between the two-line generated banner and the first import. */
function insertBlankLineAfterGeneratedBanner(code: string): string {
	return code.replace(
		/^(\/\/[^\n]+\r?\n\/\/[^\n]+)\r?\n(?=import\b)/m,
		"$1\n\n",
	);
}

function printAndTranspileDatabaseModule(args: {
	statementSegments: readonly (readonly ts.Statement[])[];
	databaseFileBasename: string;
}): { tsCode: string; jsCode: string } {
	const context = createEmitContext({
		fileName: `${args.databaseFileBasename}.ts`,
	});
	const printed = args.statementSegments
		.map((segment) => printTsNodes({ nodes: segment, context }).trimEnd())
		.join("\n\n");
	let tsCode = insertBlankLineAfterGeneratedBanner(printed);
	tsCode = finalizeGeneratedSourceWithTrailingNewline(tsCode);
	const jsCode = transpileTsToJs({
		typescriptCode: tsCode,
		module: TS_EMIT_OPTIONS_GENERATED.module,
		target: TS_EMIT_OPTIONS_GENERATED.target,
	});
	return { tsCode, jsCode };
}

/**
 * Pure AST builder for a single database module.
 * Returns statement nodes and metadata without any filesystem side effects,
 * making it the primary seam for golden/snapshot tests.
 */
function buildDatabaseModuleNodes(
		dataSourceResponse: GetDataSourceResponse,
	): DatabaseModuleBuildResult {
		const { id: dataSourceId, properties } = dataSourceResponse;
		const normalizedDataSourceId = toUndashedNotionId(dataSourceId);

		const columns: GeneratedColumnMetadataMap =
			{};
		const enumConstStatements: ts.Statement[] = [];

		const databaseName = getDataSourceDisplayName({
			dataSourceResponse,
			normalizedDataSourceId,
		});

		const databaseModuleName = camelize(databaseName);

		Object.entries(properties).forEach(([propertyName, value], index) => {
			const unsupportedPropertyType = value.type;
			if (!isSupportedNotionProperty(value)) {
				console.error(`${index === 0 ? "\n" : ""}
				[${databaseModuleName}] Property '${propertyName}' with type '${unsupportedPropertyType}' is not supported and will be skipped.`);
				return;
			}

			const propertyType: SupportedNotionColumnType = value.type;

			const camelizedColumnName = camelize(propertyName);

			const handler = propertyASTGenerators[propertyType];
			if (!handler) {
				console.warn(`No handler found for column type '${propertyType}'`);
				return;
			}

			const result = handler({
				columnName: propertyName,
				camelizedName: camelizedColumnName,
				columnValue: value,
			});
			if (!result) {
				return;
			}

			const { zodMeta, enumConstStatement } = result;
			const optionsIdentifier =
				zodMeta.type === "optionLiterals"
					? zodMeta.propertyValuesIdentifier
					: undefined;

			if (enumConstStatement) {
				enumConstStatements.push(enumConstStatement);
			}

			if (isColumnTypesWithOptions(propertyType)) {
				if (optionsIdentifier === undefined) {
					console.warn(
						`[${databaseModuleName}] Missing options identifier for '${propertyName}' (${propertyType}); skipping.`,
					);
					return;
				}
				columns[camelizedColumnName] = {
					columnName: propertyName,
					type: propertyType,
					optionsIdentifier,
				};
			} else if (value.type === "relation") {
				columns[camelizedColumnName] = {
					columnName: propertyName,
					type: "relation",
					relatedDatabaseId: toNotionDatabaseId(
						value.relation.database_id,
					),
				};
			} else {
				if (propertyType === "relation") {
					throw new Error(
						`[${databaseModuleName}] Internal error: relation column '${propertyName}' reached plain-metadata branch.`,
					);
				}
				columns[camelizedColumnName] = {
					columnName: propertyName,
					type: propertyType,
				};
			}
		});

		const queryAndPropertyTypesImport = createTypeOnlyNamedImports({
			names: [
				"DatabaseColumns",
				"DatabaseDefinition",
				"InferCreateSchema",
				"InferDatabaseSchema",
				"Query",
			],
			path: AST_IMPORT_PATHS.DATABASE_CLIENT,
		});
		const databaseClientImport = createNameImport({
			namedImport: "DatabaseClient",
			path: AST_IMPORT_PATHS.DATABASE_CLIENT,
		});
		addGeneratedDatabaseModuleBanner(
			queryAndPropertyTypesImport,
			AST_RUNTIME_CONSTANTS.CLI_GENERATE_COMMAND,
		);

		if (enumConstStatements.length > 0) {
			addLeadingSectionComment(
				enumConstStatements[0],
				"Option literals for select/status/multi_select columns",
			);
		}

		const columnNameToColumnPropertiesStatement = ts.factory.createVariableStatement(
			undefined,
			createColumnNameToColumnProperties(columns),
		);
		addLeadingSectionComment(
			columnNameToColumnPropertiesStatement,
			"Column metadata",
		);

		const pageSchemaTypeAlias = createPageSchemaTypeExport();
		addLeadingSectionComment(
			pageSchemaTypeAlias,
			"Row types (TypeScript)",
		);

		const createSchemaTypeAlias = createCreateSchemaTypeExport();
		addLeadingSectionComment(
			createSchemaTypeAlias,
			"Create/update payload types (writable columns only)",
		);

		const queryTypeExportStatement = createQuerySchemaTypeExport();
		addLeadingSectionComment(
			queryTypeExportStatement,
			"Typed database query arguments",
		);

		const databaseFactoryStatement = createDatabaseClassExport({
			databaseName: toPascalCase(databaseModuleName),
			schemaTitle: databaseName,
			databaseId: normalizedDataSourceId,
		});
		addLeadingSectionComment(
			databaseFactoryStatement,
			"Database client factory",
		);

		const statementSegments: ts.Statement[][] = [
			[queryAndPropertyTypesImport, databaseClientImport],
			...enumConstStatements.map((stmt) => [stmt]),
			[columnNameToColumnPropertiesStatement],
			[
				pageSchemaTypeAlias,
				createSchemaTypeAlias,
				queryTypeExportStatement,
				databaseFactoryStatement,
			],
		];

		return {
			statementSegments,
			databaseName,
			databaseModuleName,
			databaseId: normalizedDataSourceId,
		};
	}

/**
 * Renders the generated database module to TS and JS source text without
 * writing to disk. Used by golden tests and any caller that needs the
 * emitted code as strings.
 */
export function renderDatabaseModule(
	dataSourceResponse: GetDataSourceResponse,
): {
	tsCode: string;
	jsCode: string;
	databaseName: string;
	databaseModuleName: string;
	databaseId: string;
} {
	const { statementSegments, databaseName, databaseModuleName, databaseId } =
		buildDatabaseModuleNodes(dataSourceResponse);
	const { tsCode, jsCode } = printAndTranspileDatabaseModule({
		statementSegments,
		databaseFileBasename: toPascalCase(databaseModuleName),
	});
	return { tsCode, jsCode, databaseName, databaseModuleName, databaseId };
}

/**
 * Creates the generated module for a single database and writes it to disk.
 * Thin wrapper over the pure builders that adds filesystem I/O.
 */
export async function createTypescriptFileForDatabase(
	dataSourceResponse: GetDataSourceResponse,
) {
	const { statementSegments, databaseName, databaseModuleName, databaseId } =
		buildDatabaseModuleNodes(dataSourceResponse);

	const databasesDir = AST_FS_PATHS.DATABASES_DIR;
	if (!fs.existsSync(databasesDir)) {
		fs.mkdirSync(databasesDir, { recursive: true });
	}

	const databaseFileBasename = toPascalCase(databaseModuleName);
	const { tsCode, jsCode } = printAndTranspileDatabaseModule({
		statementSegments,
		databaseFileBasename,
	});
	const tsPath = path.resolve(databasesDir, `${databaseFileBasename}.ts`);
	const jsPath = path.resolve(databasesDir, `${databaseFileBasename}.js`);
	writeTextArtifact({ filePath: tsPath, content: tsCode });
	writeTextArtifact({ filePath: jsPath, content: jsCode });

	return {
		databaseName,
		databaseModuleName,
		databaseId,
	};
}
