/**
 * Database file writer for generated Notion data sources.
 * Converts a Notion schema response into emitted TS/JS modules, runtime Zod
 * validation, and metadata used by the generated client layer.
 */
import type {
	DataSourceObjectResponse,
	GetDataSourceResponse,
} from "@notionhq/client/build/src/api-endpoints.js";
import fs from "fs";
import path from "path";
import * as ts from "typescript";
import {
	type DatabasePropertyType,
	isSupportedPropertyType,
	type SupportedNotionColumnType,
} from "../../client/database/types";
import { camelize, toUndashedNotionId } from "../../helpers";
import {
	createColumnNameToColumnProperties,
	createColumnNameToColumnType,
	createDatabaseClassExport,
	createDatabaseIdVariable,
	createNameImport,
	createQueryTypeExport,
	createTypeOnlyNamedImports,
	toPascalCase,
} from "../shared/ast-builders";
import {
	AST_FS_PATHS,
	AST_IMPORT_PATHS,
	AST_RUNTIME_CONSTANTS,
} from "../shared/constants";
import {
	createEmitContext,
	finalizeGeneratedSourceWithTrailingNewline,
	printTsNodes,
	transpileTsToJs,
	writeTextArtifact,
} from "../shared/emit/ts-emit-core";
import { TS_EMIT_OPTIONS_GENERATED } from "../shared/emit/ts-emit-options";
import {
	propertyASTGenerators,
	type SupportedNotionProperty,
} from "./notion-column-generators";
import { createZodSchema, type ZodMetadata } from "./zod-schema";

type PropertyNameToColumnMetadataMap = Record<
	string,
	{ columnName: string; type: DatabasePropertyType }
>;

type NotionDataSourceProperty = DataSourceObjectResponse["properties"][string];

/** Narrows Notion properties to the subset supported by our emitters. */
function isSupportedNotionProperty(
	property: NotionDataSourceProperty,
): property is SupportedNotionProperty {
	return isSupportedPropertyType(property.type);
}

function addLeadingSectionComment(node: ts.Statement, text: string): void {
	ts.addSyntheticLeadingComment(
		node,
		ts.SyntaxKind.SingleLineCommentTrivia,
		` ${text}`,
		true,
	);
}

function addGeneratedDatabaseModuleBanner(
	notionOrmImport: ts.ImportDeclaration,
	cliGenerateCommand: string,
): void {
	ts.addSyntheticLeadingComment(
		notionOrmImport,
		ts.SyntaxKind.SingleLineCommentTrivia,
		" Generated by @haustle/notion-orm — do not edit manually.",
		true,
	);
	ts.addSyntheticLeadingComment(
		notionOrmImport,
		ts.SyntaxKind.SingleLineCommentTrivia,
		` Regenerate with \`${cliGenerateCommand}\` (or your package script).`,
		true,
	);
}

/**
 * Prefer the live Notion title when present, but fall back to a stable label so
 * generation can still succeed for sparse payloads.
 */
function getDataSourceDisplayName(args: {
	dataSourceResponse: GetDataSourceResponse;
	normalizedDataSourceId: string;
}): string {
	if ("title" in args.dataSourceResponse) {
		const title = args.dataSourceResponse.title?.[0]?.plain_text?.trim();
		if (title) {
			return title;
		}
	}
	return `Database ${args.normalizedDataSourceId.slice(0, 8)}`;
}

export interface DatabaseModuleBuildResult {
	/** Statement groups printed with a blank line between groups for readability. */
	statementSegments: readonly (readonly ts.Statement[])[];
	databaseName: string;
	databaseModuleName: string;
	databaseId: string;
}

/** Inserts a blank line between the two-line generated banner and the first import. */
function insertBlankLineAfterGeneratedBanner(code: string): string {
	return code.replace(
		/^(\/\/[^\n]+\r?\n\/\/[^\n]+)\r?\n(?=import\b)/m,
		"$1\n\n",
	);
}

function printAndTranspileDatabaseModule(args: {
	statementSegments: readonly (readonly ts.Statement[])[];
	databaseFileBasename: string;
}): { tsCode: string; jsCode: string } {
	const context = createEmitContext({
		fileName: `${args.databaseFileBasename}.ts`,
	});
	const printed = args.statementSegments
		.map((segment) => printTsNodes({ nodes: segment, context }).trimEnd())
		.join("\n\n");
	let tsCode = insertBlankLineAfterGeneratedBanner(printed);
	tsCode = finalizeGeneratedSourceWithTrailingNewline(tsCode);
	const jsCode = transpileTsToJs({
		typescriptCode: tsCode,
		module: TS_EMIT_OPTIONS_GENERATED.module,
		target: TS_EMIT_OPTIONS_GENERATED.target,
	});
	return { tsCode, jsCode };
}

/**
 * Pure AST builder for a single database module.
 * Returns statement nodes and metadata without any filesystem side effects,
 * making it the primary seam for golden/snapshot tests.
 */
export function buildDatabaseModuleNodes(
		dataSourceResponse: GetDataSourceResponse,
	): DatabaseModuleBuildResult {
		const { id: dataSourceId, properties } = dataSourceResponse;
		const normalizedDataSourceId = toUndashedNotionId(dataSourceId);

		const camelPropertyNameToNameAndTypeMap: PropertyNameToColumnMetadataMap =
			{};
		const enumConstStatements: ts.Statement[] = [];
		const zodColumns: ZodMetadata[] = [];

		const databaseName = getDataSourceDisplayName({
			dataSourceResponse,
			normalizedDataSourceId,
		});

		const databaseModuleName = camelize(databaseName);

		const databaseColumnTypeProps: ts.TypeElement[] = [];

		Object.entries(properties).forEach(([propertyName, value], index) => {
			const unsupportedPropertyType = value.type;
			if (!isSupportedNotionProperty(value)) {
				console.error(`${index === 0 ? "\n" : ""}
				[${databaseModuleName}] Property '${propertyName}' with type '${unsupportedPropertyType}' is not supported and will be skipped.`);
				return;
			}

			const propertyType: SupportedNotionColumnType = value.type;

			const camelizedColumnName = camelize(propertyName);

			camelPropertyNameToNameAndTypeMap[camelizedColumnName] = {
				columnName: propertyName,
				type: propertyType,
			};

			const handler = propertyASTGenerators[propertyType];
			if (!handler) {
				console.warn(`No handler found for column type '${propertyType}'`);
				return;
			}

			const result = handler({
				columnName: propertyName,
				camelizedName: camelizedColumnName,
				columnValue: value,
			});
			if (!result) {
				return;
			}

			const { tsPropertySignature, zodMeta, enumConstStatement } = result;

			databaseColumnTypeProps.push(tsPropertySignature);

			if (enumConstStatement) {
				enumConstStatements.push(enumConstStatement);
			}

			zodColumns.push({
				propName: camelizedColumnName,
				columnName: propertyName,
				type: propertyType,
				...zodMeta,
			});
		});

		const zodSchemaStatement = createZodSchema({
			identifier: "schema",
			columns: zodColumns,
		});

		const databaseSchemaTypeAlias = ts.factory.createTypeAliasDeclaration(
			[ts.factory.createToken(ts.SyntaxKind.ExportKeyword)],
			ts.factory.createIdentifier("DatabaseSchemaType"),
			undefined,
			ts.factory.createTypeLiteralNode(databaseColumnTypeProps),
		);

		const queryAndPropertyTypesImport = createTypeOnlyNamedImports({
			names: ["Query", "DatabasePropertyType"],
			path: AST_IMPORT_PATHS.DATABASE_CLIENT,
		});
		const databaseClientImport = createNameImport({
			namedImport: "DatabaseClient",
			path: AST_IMPORT_PATHS.DATABASE_CLIENT,
		});
		addGeneratedDatabaseModuleBanner(
			queryAndPropertyTypesImport,
			AST_RUNTIME_CONSTANTS.CLI_GENERATE_COMMAND,
		);

		const zodImport = createNameImport({
			namedImport: "z",
			path: AST_IMPORT_PATHS.ZOD,
		});

		const idStatement = createDatabaseIdVariable(normalizedDataSourceId);
		addLeadingSectionComment(
			idStatement,
			"Identity (Notion data source id)",
		);

		if (enumConstStatements.length > 0) {
			addLeadingSectionComment(
				enumConstStatements[0],
				"Option literals for select/status/multi_select columns",
			);
		}

		addLeadingSectionComment(
			databaseSchemaTypeAlias,
			"Row types (TypeScript)",
		);

		const columnNameToColumnPropertiesStatement = ts.factory.createVariableStatement(
			undefined,
			createColumnNameToColumnProperties(camelPropertyNameToNameAndTypeMap),
		);
		addLeadingSectionComment(
			columnNameToColumnPropertiesStatement,
			"Column metadata",
		);

		const columnNameToColumnTypeStatement = createColumnNameToColumnType();
		addLeadingSectionComment(
			columnNameToColumnTypeStatement,
			"Derived column types (for query filters/sorts)",
		);

		const queryTypeExportStatement = createQueryTypeExport();
		addLeadingSectionComment(
			queryTypeExportStatement,
			"Typed database query arguments",
		);

		addLeadingSectionComment(zodSchemaStatement, "Runtime validation (Zod)");

		const databaseFactoryStatement = createDatabaseClassExport({
			databaseName: toPascalCase(databaseModuleName),
			schemaTitle: databaseName,
		});
		addLeadingSectionComment(
			databaseFactoryStatement,
			"Database client factory",
		);

		const statementSegments: ts.Statement[][] = [
			[queryAndPropertyTypesImport, databaseClientImport, zodImport],
			[databaseFactoryStatement],
			[idStatement],
			...enumConstStatements.map((stmt) => [stmt]),
			[databaseSchemaTypeAlias],
			[columnNameToColumnPropertiesStatement],
			[columnNameToColumnTypeStatement],
			[queryTypeExportStatement],
			[zodSchemaStatement],
		];

		return {
			statementSegments,
			databaseName,
			databaseModuleName,
			databaseId: normalizedDataSourceId,
		};
	}

/**
 * Renders the generated database module to TS and JS source text without
 * writing to disk. Used by golden tests and any caller that needs the
 * emitted code as strings.
 */
export function renderDatabaseModule(
	dataSourceResponse: GetDataSourceResponse,
): {
	tsCode: string;
	jsCode: string;
	databaseName: string;
	databaseModuleName: string;
	databaseId: string;
} {
	const { statementSegments, databaseName, databaseModuleName, databaseId } =
		buildDatabaseModuleNodes(dataSourceResponse);
	const { tsCode, jsCode } = printAndTranspileDatabaseModule({
		statementSegments,
		databaseFileBasename: toPascalCase(databaseModuleName),
	});
	return { tsCode, jsCode, databaseName, databaseModuleName, databaseId };
}

/**
 * Creates the generated module for a single database and writes it to disk.
 * Thin wrapper over the pure builders that adds filesystem I/O.
 */
export async function createTypescriptFileForDatabase(
	dataSourceResponse: GetDataSourceResponse,
) {
	const { statementSegments, databaseName, databaseModuleName, databaseId } =
		buildDatabaseModuleNodes(dataSourceResponse);

	const databasesDir = AST_FS_PATHS.DATABASES_DIR;
	if (!fs.existsSync(databasesDir)) {
		fs.mkdirSync(databasesDir, { recursive: true });
	}

	const databaseFileBasename = toPascalCase(databaseModuleName);
	const { tsCode, jsCode } = printAndTranspileDatabaseModule({
		statementSegments,
		databaseFileBasename,
	});
	const tsPath = path.resolve(databasesDir, `${databaseFileBasename}.ts`);
	const jsPath = path.resolve(databasesDir, `${databaseFileBasename}.js`);
	writeTextArtifact({ filePath: tsPath, content: tsCode });
	writeTextArtifact({ filePath: jsPath, content: jsCode });

	return {
		databaseName,
		databaseModuleName,
		databaseId,
	};
}
